// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Questionnairor.Data;
using System;

namespace Questionnairor.Migrations
{
    [DbContext(typeof(QuestionnaireDbContext))]
    partial class QuestionnaireDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Questionnairor.Models.Choice", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<bool>("IsDefault");

                    b.Property<Guid?>("QuestionId");

                    b.Property<string>("Text");

                    b.Property<int>("Value");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Choices");
                });

            modelBuilder.Entity("Questionnairor.Models.Question", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<int?>("Answer");

                    b.Property<Guid?>("QuestionnaireId");

                    b.Property<string>("Text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.HasIndex("QuestionnaireId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Questionnairor.Models.Questionnaire", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Conclusion");

                    b.Property<string>("Introduction");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("Questionnaires");
                });

            modelBuilder.Entity("Questionnairor.Models.Response", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<Guid?>("ChoiceId");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<int>("MinimumChoices");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("ChoiceId");

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("Questionnairor.Models.Choice", b =>
                {
                    b.HasOne("Questionnairor.Models.Question")
                        .WithMany("Choices")
                        .HasForeignKey("QuestionId");
                });

            modelBuilder.Entity("Questionnairor.Models.Question", b =>
                {
                    b.HasOne("Questionnairor.Models.Questionnaire")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionnaireId");
                });

            modelBuilder.Entity("Questionnairor.Models.Response", b =>
                {
                    b.HasOne("Questionnairor.Models.Choice")
                        .WithMany("Responses")
                        .HasForeignKey("ChoiceId");
                });
#pragma warning restore 612, 618
        }
    }
}
